import type { Metadata } from "next"

import { geistMono, geistSans } from "@/lib/fonts"

import "@/styles/globals.css"

export const metadata: Metadata = {
  title: "NextJS 15 Started",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      className="scroll-smooth"
      data-scroll-behavior="smooth"
      dir="ltr"
      lang="en"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
